char locations[][100] = {
		"Abha",
		"Abidjan",
		"Abéché",
		"Accra",
		"Addis Ababa",
		"Adelaide",
		"Aden",
		"Ahvaz",
		"Albuquerque",
		"Alexandra",
		"Alexandria",
		"Algiers",
		"Alice Springs",
		"Almaty",
		"Amsterdam",
		"Anadyr",
		"Anchorage",
		"Andorra la Vella",
		"Ankara",
		"Antananarivo",
		"Antsiranana",
		"Arkhangelsk",
		"Ashgabat",
		"Asmara",
		"Assab",
		"Astana",
		"Athens",
		"Atlanta",
		"Auckland",
		"Austin",
		"Baghdad",
		"Baguio",
		"Baku",
		"Baltimore",
		"Bamako",
		"Bangkok",
		"Bangui",
		"Banjul",
		"Barcelona",
		"Bata",
		"Batumi",
		"Beijing",
		"Beirut",
		"Belgrade",
		"Belize City",
		"Benghazi",
		"Bergen",
		"Berlin",
		"Bilbao",
		"Birao",
		"Bishkek",
		"Bissau",
		"Blantyre",
		"Bloemfontein",
		"Boise",
		"Bordeaux",
		"Bosaso",
		"Boston",
		"Bouaké",
		"Bratislava",
		"Brazzaville",
		"Bridgetown",
		"Brisbane",
		"Brussels",
		"Bucharest",
		"Budapest",
		"Bujumbura",
		"Bulawayo",
		"Burnie",
		"Busan",
		"Cabo San Lucas",
		"Cairns",
		"Cairo",
		"Calgary",
		"Canberra",
		"Cape Town",
		"Changsha",
		"Charlotte",
		"Chiang Mai",
		"Chicago",
		"Chihuahua",
		"Chișinău",
		"Chittagong",
		"Chongqing",
		"Christchurch",
		"City of San Marino",
		"Colombo",
		"Columbus",
		"Conakry",
		"Copenhagen",
		"Cotonou",
		"Cracow",
		"Da Lat",
		"Da Nang",
		"Dakar",
		"Dallas",
		"Damascus",
		"Dampier",
		"Dar es Salaam",
		"Darwin",
		"Denpasar",
		"Denver",
		"Detroit",
		"Dhaka",
		"Dikson",
		"Dili",
		"Djibouti",
		"Dodoma",
		"Dolisie",
		"Douala",
		"Dubai",
		"Dublin",
		"Dunedin",
		"Durban",
		"Dushanbe",
		"Edinburgh",
		"Edmonton",
		"El Paso",
		"Entebbe",
		"Erbil",
		"Erzurum",
		"Fairbanks",
		"Fianarantsoa",
		"Flores,  Petén",
		"Frankfurt",
		"Fresno",
		"Fukuoka",
		"Gabès",
		"Gaborone",
		"Gagnoa",
		"Gangtok",
		"Garissa",
		"Garoua",
		"George Town",
		"Ghanzi",
		"Gjoa Haven",
		"Guadalajara",
		"Guangzhou",
		"Guatemala City",
		"Halifax",
		"Hamburg",
		"Hamilton",
		"Hanga Roa",
		"Hanoi",
		"Harare",
		"Harbin",
		"Hargeisa",
		"Hat Yai",
		"Havana",
		"Helsinki",
		"Heraklion",
		"Hiroshima",
		"Ho Chi Minh City",
		"Hobart",
		"Hong Kong",
		"Honiara",
		"Honolulu",
		"Houston",
		"Ifrane",
		"Indianapolis",
		"Iqaluit",
		"Irkutsk",
		"Istanbul",
		"İzmir",
		"Jacksonville",
		"Jakarta",
		"Jayapura",
		"Jerusalem",
		"Johannesburg",
		"Jos",
		"Juba",
		"Kabul",
		"Kampala",
		"Kandi",
		"Kankan",
		"Kano",
		"Kansas City",
		"Karachi",
		"Karonga",
		"Kathmandu",
		"Khartoum",
		"Kingston",
		"Kinshasa",
		"Kolkata",
		"Kuala Lumpur",
		"Kumasi",
		"Kunming",
		"Kuopio",
		"Kuwait City",
		"Kyiv",
		"Kyoto",
		"La Ceiba",
		"La Paz",
		"Lagos",
		"Lahore",
		"Lake Havasu City",
		"Lake Tekapo",
		"Las Palmas de Gran Canaria",
		"Las Vegas",
		"Launceston",
		"Lhasa",
		"Libreville",
		"Lisbon",
		"Livingstone",
		"Ljubljana",
		"Lodwar",
		"Lomé",
		"London",
		"Los Angeles",
		"Louisville",
		"Luanda",
		"Lubumbashi",
		"Lusaka",
		"Luxembourg City",
		"Lviv",
		"Lyon",
		"Madrid",
		"Mahajanga",
		"Makassar",
		"Makurdi",
		"Malabo",
		"Malé",
		"Managua",
		"Manama",
		"Mandalay",
		"Mango",
		"Manila",
		"Maputo",
		"Marrakesh",
		"Marseille",
		"Maun",
		"Medan",
		"Mek'ele",
		"Melbourne",
		"Memphis",
		"Mexicali",
		"Mexico City",
		"Miami",
		"Milan",
		"Milwaukee",
		"Minneapolis",
		"Minsk",
		"Mogadishu",
		"Mombasa",
		"Monaco",
		"Moncton",
		"Monterrey",
		"Montreal",
		"Moscow",
		"Mumbai",
		"Murmansk",
		"Muscat",
		"Mzuzu",
		"N'Djamena",
		"Naha",
		"Nairobi",
		"Nakhon Ratchasima",
		"Napier",
		"Napoli",
		"Nashville",
		"Nassau",
		"Ndola",
		"New Delhi",
		"New Orleans",
		"New York City",
		"Ngaoundéré",
		"Niamey",
		"Nicosia",
		"Niigata",
		"Nouadhibou",
		"Nouakchott",
		"Novosibirsk",
		"Nuuk",
		"Odesa",
		"Odienné",
		"Oklahoma City",
		"Omaha",
		"Oranjestad",
		"Oslo",
		"Ottawa",
		"Ouagadougou",
		"Ouahigouya",
		"Ouarzazate",
		"Oulu",
		"Palembang",
		"Palermo",
		"Palm Springs",
		"Palmerston North",
		"Panama City",
		"Parakou",
		"Paris",
		"Perth",
		"Petropavlovsk-Kamchatsky",
		"Philadelphia",
		"Phnom Penh",
		"Phoenix",
		"Pittsburgh",
		"Podgorica",
		"Pointe-Noire",
		"Pontianak",
		"Port Moresby",
		"Port Sudan",
		"Port Vila",
		"Port-Gentil",
		"Portland OR}",
		"Porto",
		"Prague",
		"Praia",
		"Pretoria",
		"Pyongyang",
		"Rabat",
		"Rangpur",
		"Reggane",
		"Reykjavík",
		"Riga",
		"Riyadh",
		"Rome",
		"Roseau",
		"Rostov-on-Don",
		"Sacramento",
		"Saint Petersburg",
		"Saint-Pierre",
		"Salt Lake City",
		"San Antonio",
		"San Diego",
		"San Francisco",
		"San Jose",
		"San José",
		"San Juan",
		"San Salvador",
		"Sana'a",
		"Santo Domingo",
		"Sapporo",
		"Sarajevo",
		"Saskatoon",
		"Seattle",
		"Ségou",
		"Seoul",
		"Seville",
		"Shanghai",
		"Singapore",
		"Skopje",
		"Sochi",
		"Sofia",
		"Sokoto",
		"Split",
		"St. John's",
		"St. Louis",
		"Stockholm",
		"Surabaya",
		"Suva",
		"Suwałki",
		"Sydney",
		"Tabora",
		"Tabriz",
		"Taipei",
		"Tallinn",
		"Tamale",
		"Tamanrasset",
		"Tampa",
		"Tashkent",
		"Tauranga",
		"Tbilisi",
		"Tegucigalpa",
		"Tehran",
		"Tel Aviv",
		"Thessaloniki",
		"Thiès",
		"Tijuana",
		"Timbuktu",
		"Tirana",
		"Toamasina",
		"Tokyo",
		"Toliara",
		"Toluca",
		"Toronto",
		"Tripoli",
		"Tromsø",
		"Tucson",
		"Tunis",
		"Ulaanbaatar",
		"Upington",
		"Ürümqi",
		"Vaduz",
		"Valencia",
		"Valletta",
		"Vancouver",
		"Veracruz",
		"Vienna",
		"Vientiane",
		"Villahermosa",
		"Vilnius",
		"Virginia Beach",
		"Vladivostok",
		"Warsaw",
		"Washington, D.C.",
		"Wau",
		"Wellington",
		"Whitehorse",
		"Wichita",
		"Willemstad",
		"Winnipeg",
		"Wrocław",
		"Xi'an",
		"Yakutsk",
		"Yangon",
		"Yaoundé",
		"Yellowknife",
		"Yerevan",
		"Yinchuan",
		"Zagreb",
		"Zanzibar City",
		"Zürich",
};

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#define MAGIC_HASHMAP_SIZE 2636
#define NUM_CITIES 413

typedef struct
{
	float sum;
	float min;
	float max;
	int count;
} measurements;

typedef measurements *magic_hashmap;

void process_line(char *line, magic_hashmap measures);
void output_file(magic_hashmap measures);

size_t hash(const char *key)
{
	unsigned long hash = 5381;
	char c;
	while ((c = *key++))
		hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
	return hash % MAGIC_HASHMAP_SIZE;
}

int main()
{
	magic_hashmap measures = (measurements *)calloc(MAGIC_HASHMAP_SIZE, sizeof(measurements));

	FILE *file = fopen("measurements.txt", "r");
	if (file == NULL)
	{
		printf("failed to open measurements file");
		return EXIT_FAILURE;
	}

	char *line = NULL;
	size_t n;
	while (getline(&line, &n, file) != EOF)
	{
		process_line(line, measures);
	}

	output_file(measures);
	free(measures);
	free(line);
	fclose(file);
	return EXIT_SUCCESS;
}

void process_line(char *line, magic_hashmap measures)
{
	char city[101];
	float temp;

	sscanf(line, "%[^;];%f", city, &temp);

	line = city;

	measurements *current = &measures[hash(line)];
	current->sum += temp;
	current->count++;

	if (current->max < temp)
		current->max = temp;

	if (current->min > temp)
		current->min = temp;
}

void output_file(magic_hashmap measures)
{
	measurements temp;
	FILE *out_file = fopen("output.txt", "w");
	for (int i = 0; i < NUM_CITIES; i++)
	{
		temp = measures[hash(locations[i])];
		fprintf(out_file, "%s;%f;%f;%f\n", locations[i], temp.min, ceilf((temp.sum / temp.count) * 10) / 10, temp.max);
	}
	fclose(out_file);
}
